/**
 * MCP Tool Definitions
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by the Wireweave team.
 * To request changes, please open an issue at:
 * https://github.com/wireweave/mcp-server/issues
 *
 * Generated: 2026-05-17T13:36:37.806Z
 * Public tools: 32 (local: 9, server: 23)
 */

import type { Tool } from '@modelcontextprotocol/sdk/types.js'

// Tool definitions
export const tools: Tool[] = [
  {
    name: 'wireweave_parse',
    description: 'Parse Wireweave DSL source code into an AST (Abstract Syntax Tree)',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to parse',
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_validate',
    description:
      'Validate Wireweave DSL syntax without generating output. Use strict mode to also check for unknown attributes.',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to validate',
        },
        strict: {
          type: 'boolean',
          description:
            'Enable strict mode to also validate that only known attributes are used. Recommended for catching typos and incorrect attribute names.',
          default: false,
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_grammar',
    description: 'Get the Wireweave DSL grammar documentation and syntax reference',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_guide',
    description:
      'Get the comprehensive LLM guide for Wireweave DSL. This is the PRIMARY resource for learning the language - includes syntax, components, patterns, and best practices. Call this FIRST before generating wireframes.',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_patterns',
    description:
      'Get common layout patterns for wireframes including headers, sidebars, forms, cards, and more. Use these as building blocks.',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_examples',
    description:
      'Get Wireweave code examples. Use this to learn patterns and best practices for different UI types.',
    inputSchema: {
      type: 'object',
      properties: {
        category: {
          type: 'string',
          enum: ['all', 'basic', 'layout', 'navigation', 'form', 'dashboard'],
          description:
            'Filter examples by category. Use "all" to get all examples. Categories cover generic component compositions (basic, layout, navigation, form) and a domain-agnostic dashboard shell.',
          default: 'all',
        },
        limit: {
          type: 'number',
          description: 'Maximum number of examples to return',
          default: 5,
        },
      },
      required: [],
    },
  },
  {
    name: 'wireweave_list_components',
    description:
      'List Wireweave DSL components with their categories, attributes, and examples. Use this to discover available components for wireframe generation. Filter by category (layout, navigation, form, etc.) when narrowing the search.',
    inputSchema: {
      type: 'object',
      properties: {
        category: {
          type: 'string',
          description:
            'Filter components by category (e.g., "layout", "navigation", "form", "content", "interaction"). Omit to return all components.',
        },
      },
      required: [],
    },
  },
  {
    name: 'wireweave_render_html_code',
    description:
      'Render Wireweave DSL to HTML code. Returns the HTML content directly. This is an alias for wireweave_render_html with explicit naming.',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to render',
        },
        theme: {
          type: 'string',
          enum: ['light', 'dark'],
          description: 'Color theme for rendering',
          default: 'light',
        },
        fullDocument: {
          type: 'boolean',
          description: 'Return a complete HTML document instead of fragment',
          default: false,
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_validate_ux',
    description:
      'Validate Wireweave DSL for UX best practices. Returns issues with severity levels and actionable recommendations.',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to validate',
        },
        categories: {
          type: 'array',
          items: {
            type: 'string',
            enum: [
              'accessibility',
              'usability',
              'form',
              'touch-target',
              'consistency',
              'navigation',
              'feedback',
              'content',
              'data-display',
              'interaction',
            ],
          },
          description: 'UX rule categories to check. If not specified, all categories are checked.',
        },
        minSeverity: {
          type: 'string',
          enum: ['error', 'warning', 'info'],
          description: 'Minimum severity level to report',
          default: 'info',
        },
        maxIssues: {
          type: 'number',
          description: 'Maximum number of issues to return',
        },
        disabledRules: {
          type: 'array',
          items: {
            type: 'string',
          },
          description:
            'List of rule IDs to disable (e.g., ["a11y-input-label", "form-submit-button"])',
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_ux_rules',
    description: 'Get available UX rule categories and their descriptions',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_diff',
    description: 'Compare two Wireweave DSL sources and return the differences between them',
    inputSchema: {
      type: 'object',
      properties: {
        oldSource: {
          type: 'string',
          description: 'The original Wireweave DSL source code',
        },
        newSource: {
          type: 'string',
          description: 'The modified Wireweave DSL source code',
        },
        ignoreAttributes: {
          type: 'boolean',
          description: 'Ignore attribute changes, only compare structure',
          default: false,
        },
        ignoreOrder: {
          type: 'boolean',
          description: 'Ignore the order of children when comparing',
          default: false,
        },
      },
      required: ['oldSource', 'newSource'],
    },
  },
  {
    name: 'wireweave_export_json',
    description: 'Export Wireweave DSL to JSON format',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to export',
        },
        includeLocations: {
          type: 'boolean',
          description: 'Include source location information in output',
          default: false,
        },
        prettyPrint: {
          type: 'boolean',
          description: 'Format JSON with indentation',
          default: true,
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_export_figma',
    description: 'Export Wireweave DSL to Figma-compatible format',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to export',
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_analyze',
    description:
      'Analyze Wireweave DSL for statistics and metrics including component usage, tree structure, accessibility score, and complexity',
    inputSchema: {
      type: 'object',
      properties: {
        source: {
          type: 'string',
          description: 'The Wireweave DSL source code to analyze',
        },
        includeComponentBreakdown: {
          type: 'boolean',
          description: 'Include detailed component usage breakdown',
          default: true,
        },
        includeAccessibility: {
          type: 'boolean',
          description: 'Include accessibility analysis',
          default: true,
        },
        includeComplexity: {
          type: 'boolean',
          description: 'Include complexity metrics',
          default: true,
        },
        includeLayout: {
          type: 'boolean',
          description: 'Include layout pattern analysis',
          default: true,
        },
        includeContent: {
          type: 'boolean',
          description: 'Include content analysis',
          default: true,
        },
      },
      required: ['source'],
    },
  },
  {
    name: 'wireweave_cloud_list_projects',
    description:
      'List all your Wireweave projects. Projects help organize your wireframes. WORKFLOW: Call this first before saving wireframes. If the list is empty, ask the user whether to create a new project (call wireweave_cloud_create_project) or use the default project.',
    inputSchema: {
      type: 'object',
      properties: {
        includeArchived: {
          type: 'boolean',
          description: 'Include archived projects',
          default: false,
        },
      },
      required: [],
    },
  },
  {
    name: 'wireweave_cloud_create_project',
    description:
      'Create a new project to organize wireframes. Use this when the user wants to organize their wireframes into a specific project. The project can have a custom name, description, and color.',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Project name',
        },
        description: {
          type: 'string',
          description: 'Project description',
        },
        color: {
          type: 'string',
          description: 'Project color (hex code, e.g., #6366f1)',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'wireweave_cloud_update_project',
    description: 'Update an existing project',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'Project ID to update',
        },
        name: {
          type: 'string',
          description: 'New project name',
        },
        description: {
          type: 'string',
          description: 'New project description',
        },
        color: {
          type: 'string',
          description: 'New project color (hex code)',
        },
        isArchived: {
          type: 'boolean',
          description: 'Archive or unarchive the project',
        },
      },
      required: ['id'],
    },
  },
  {
    name: 'wireweave_cloud_list_wireframes',
    description: 'List your saved wireframes. Optionally filter by project or tags.',
    inputSchema: {
      type: 'object',
      properties: {
        projectId: {
          type: 'string',
          description: 'Filter by project ID',
        },
        tags: {
          type: 'array',
          items: {
            type: 'string',
          },
          description: 'Filter by tags',
        },
        limit: {
          type: 'number',
          description: 'Maximum number of wireframes to return',
          default: 20,
        },
        offset: {
          type: 'number',
          description: 'Offset for pagination',
          default: 0,
        },
      },
      required: [],
    },
  },
  {
    name: 'wireweave_cloud_get_wireframe',
    description: 'Get a specific wireframe by ID, including its code and metadata',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'Wireframe ID',
        },
      },
      required: ['id'],
    },
  },
  {
    name: 'wireweave_cloud_save_wireframe',
    description:
      "Save a new wireframe to the cloud. Free (v2.0+).\n\nRECOMMENDED WORKFLOW:\n1. Call wireweave_cloud_list_projects to get available projects\n2. If projects exist: Ask user which project to save to\n3. If no projects: Ask user to (a) create a new project, or (b) save to default project\n4. Call this tool with the chosen projectId (or omit for default project)\n\nNote: If projectId is not provided, the wireframe will be saved to the user's default project.",
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Wireframe name',
        },
        code: {
          type: 'string',
          description: 'Wireweave DSL code',
        },
        description: {
          type: 'string',
          description: 'Wireframe description',
        },
        projectId: {
          type: 'string',
          description:
            'Project ID to save to. Get available projects using wireweave_cloud_list_projects first.',
        },
        tags: {
          type: 'array',
          items: {
            type: 'string',
          },
          description: 'Tags for categorization',
        },
        isPublic: {
          type: 'boolean',
          description: 'Make wireframe publicly visible',
          default: false,
        },
      },
      required: ['name', 'code'],
    },
  },
  {
    name: 'wireweave_cloud_update_wireframe',
    description: 'Update an existing wireframe. Creates a new version automatically. Free (v2.0+).',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'Wireframe ID to update',
        },
        name: {
          type: 'string',
          description: 'New name (optional)',
        },
        code: {
          type: 'string',
          description: 'New Wireweave DSL code (optional)',
        },
        description: {
          type: 'string',
          description: 'New description (optional)',
        },
        tags: {
          type: 'array',
          items: {
            type: 'string',
          },
          description: 'New tags (optional)',
        },
        isPublic: {
          type: 'boolean',
          description: 'Update public visibility (optional)',
        },
      },
      required: ['id'],
    },
  },
  {
    name: 'wireweave_cloud_delete_wireframe',
    description: 'Delete a wireframe permanently',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'Wireframe ID to delete',
        },
      },
      required: ['id'],
    },
  },
  {
    name: 'wireweave_cloud_get_versions',
    description: 'Get version history of a wireframe',
    inputSchema: {
      type: 'object',
      properties: {
        wireframeId: {
          type: 'string',
          description: 'Wireframe ID',
        },
      },
      required: ['wireframeId'],
    },
  },
  {
    name: 'wireweave_cloud_restore_version',
    description: 'Restore a wireframe to a previous version. Free (v2.0+).',
    inputSchema: {
      type: 'object',
      properties: {
        wireframeId: {
          type: 'string',
          description: 'Wireframe ID',
        },
        version: {
          type: 'number',
          description: 'Version number to restore',
        },
      },
      required: ['wireframeId', 'version'],
    },
  },
  {
    name: 'wireweave_cloud_create_share_link',
    description: 'Create a shareable link for a wireframe. Free (v2.0+).',
    inputSchema: {
      type: 'object',
      properties: {
        wireframeId: {
          type: 'string',
          description: 'Wireframe ID to share',
        },
        title: {
          type: 'string',
          description: 'Custom title for the shared view',
        },
        allowCopy: {
          type: 'boolean',
          description: 'Allow viewers to copy the code',
          default: false,
        },
        password: {
          type: 'string',
          description: 'Password protection (optional)',
        },
        expiresInDays: {
          type: 'number',
          description: 'Link expiration in days (optional, null = never)',
        },
      },
      required: ['wireframeId'],
    },
  },
  {
    name: 'wireweave_cloud_list_shares',
    description: 'List share links for a wireframe',
    inputSchema: {
      type: 'object',
      properties: {
        wireframeId: {
          type: 'string',
          description: 'Wireframe ID',
        },
      },
      required: ['wireframeId'],
    },
  },
  {
    name: 'wireweave_cloud_diff_versions',
    description:
      'Compare two versions of a wireframe and return the differences. Useful for reviewing changes without loading full code.',
    inputSchema: {
      type: 'object',
      properties: {
        wireframeId: {
          type: 'string',
          description: 'Wireframe ID',
        },
        versionA: {
          type: 'number',
          description: 'First version number to compare',
        },
        versionB: {
          type: 'number',
          description: 'Second version number to compare',
        },
      },
      required: ['wireframeId', 'versionA', 'versionB'],
    },
  },
  {
    name: 'wireweave_account_balance',
    description: 'Check your current credit balance and subscription status',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_account_subscription',
    description: 'Get detailed subscription information including plan features',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_account_transactions',
    description: 'View your credit transaction history',
    inputSchema: {
      type: 'object',
      properties: {
        limit: {
          type: 'number',
          description: 'Number of transactions to return',
          default: 20,
        },
        type: {
          type: 'string',
          enum: ['purchase', 'subscription', 'usage', 'refund', 'bonus', 'admin'],
          description: 'Filter by transaction type',
        },
      },
      required: [],
    },
  },
  {
    name: 'wireweave_pricing',
    description: 'Get current pricing information for plans, credit packs, and feature costs',
    inputSchema: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  {
    name: 'wireweave_gallery',
    description: 'Browse public wireframe gallery for inspiration',
    inputSchema: {
      type: 'object',
      properties: {
        tags: {
          type: 'array',
          items: {
            type: 'string',
          },
          description: 'Filter by tags',
        },
        limit: {
          type: 'number',
          description: 'Number of wireframes to return',
          default: 20,
        },
      },
      required: [],
    },
  },
]

// Map tool names to API endpoints (all public tools — local-dispatch tools
// retain their endpoint mapping for parity with api-server routes).
export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'

export interface ToolEndpoint {
  method: HttpMethod
  path: string
  pathParams?: string[]
}

export const toolEndpoints: Record<string, ToolEndpoint> = {
  wireweave_parse: { method: 'POST', path: '/tools/parse' },
  wireweave_validate: { method: 'POST', path: '/tools/validate' },
  wireweave_grammar: { method: 'GET', path: '/tools/grammar' },
  wireweave_guide: { method: 'GET', path: '/tools/guide' },
  wireweave_patterns: { method: 'GET', path: '/tools/patterns' },
  wireweave_examples: { method: 'GET', path: '/tools/examples' },
  wireweave_list_components: { method: 'GET', path: '/tools/list-components' },
  wireweave_render_html_code: { method: 'POST', path: '/tools/render/html' },
  wireweave_validate_ux: { method: 'POST', path: '/tools/validate/ux' },
  wireweave_ux_rules: { method: 'GET', path: '/tools/ux-rules' },
  wireweave_diff: { method: 'POST', path: '/tools/diff' },
  wireweave_export_json: { method: 'POST', path: '/tools/export/json' },
  wireweave_export_figma: { method: 'POST', path: '/tools/export/figma' },
  wireweave_analyze: { method: 'POST', path: '/tools/analyze' },
  wireweave_cloud_list_projects: { method: 'GET', path: '/cloud/projects' },
  wireweave_cloud_create_project: { method: 'POST', path: '/cloud/projects' },
  wireweave_cloud_update_project: {
    method: 'PATCH',
    path: '/cloud/projects/:id',
    pathParams: ['id'],
  },
  wireweave_cloud_list_wireframes: { method: 'GET', path: '/cloud/wireframes' },
  wireweave_cloud_get_wireframe: {
    method: 'GET',
    path: '/cloud/wireframes/:id',
    pathParams: ['id'],
  },
  wireweave_cloud_save_wireframe: { method: 'POST', path: '/cloud/wireframes' },
  wireweave_cloud_update_wireframe: {
    method: 'PATCH',
    path: '/cloud/wireframes/:id',
    pathParams: ['id'],
  },
  wireweave_cloud_delete_wireframe: {
    method: 'DELETE',
    path: '/cloud/wireframes/:id',
    pathParams: ['id'],
  },
  wireweave_cloud_get_versions: {
    method: 'GET',
    path: '/cloud/wireframes/:wireframeId/versions',
    pathParams: ['wireframeId'],
  },
  wireweave_cloud_restore_version: {
    method: 'POST',
    path: '/cloud/wireframes/:wireframeId/versions/:version/restore',
    pathParams: ['wireframeId', 'version'],
  },
  wireweave_cloud_create_share_link: {
    method: 'POST',
    path: '/cloud/wireframes/:wireframeId/shares',
    pathParams: ['wireframeId'],
  },
  wireweave_cloud_list_shares: {
    method: 'GET',
    path: '/cloud/wireframes/:wireframeId/shares',
    pathParams: ['wireframeId'],
  },
  wireweave_cloud_diff_versions: {
    method: 'GET',
    path: '/cloud/wireframes/:wireframeId/diff',
    pathParams: ['wireframeId'],
  },
  wireweave_account_balance: { method: 'GET', path: '/billing/balance' },
  wireweave_account_subscription: { method: 'GET', path: '/billing/subscription' },
  wireweave_account_transactions: { method: 'GET', path: '/billing/transactions' },
  wireweave_pricing: { method: 'GET', path: '/billing/pricing' },
  wireweave_gallery: { method: 'GET', path: '/cloud/gallery' },
}

// Tool names that SDK dispatches locally (no api call).
// Source of truth: api-server/src/tool-definitions.ts (dispatch: 'local').
// Consumers (mcp-server / cli / skill) route these through @wireweave/sdk
// localDispatch instead of HTTP.
export const localToolNames: ReadonlySet<string> = new Set([
  'wireweave_parse',
  'wireweave_validate',
  'wireweave_list_components',
  'wireweave_render_html_code',
  'wireweave_validate_ux',
  'wireweave_diff',
  'wireweave_export_json',
  'wireweave_export_figma',
  'wireweave_analyze',
])
