import assert from 'node:assert/strict'
import { test } from 'node:test'
import {
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
  existsSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath, URL } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { formatGeneratedSource } from './format-generated.mjs'

/** @param {import('node:test').TestContext} context */
async function parserFixture(context) {
  const root = mkdtempSync(join(tmpdir(), 'wireweave-core4-parser-gate-'))
  context.after(() => rmSync(root, { recursive: true, force: true }))
  writeFileSync(join(root, '.prettierrc.json'), '{"semi":false,"singleQuote":true}')
  const scripts = join(root, 'scripts')
  mkdirSync(scripts)
  for (const name of ['check-generated-parser.mjs', 'format-generated.mjs']) {
    writeFileSync(join(scripts, name), readFileSync(new URL('./' + name, import.meta.url)))
  }
  symlinkSync(
    fileURLToPath(new URL('../node_modules', import.meta.url)),
    join(root, 'node_modules'),
    'junction',
  )
  const build = 'peggy --format es -o generated-parser.js grammar.peggy'
  const manifest = join(root, 'package.json')
  writeFileSync(
    manifest,
    JSON.stringify({ name: 'parser-fixture', type: 'module', scripts: { 'build:grammar': build } }),
  )
  writeFileSync(join(root, 'grammar.peggy'), 'start = "hello"')
  const require = createRequire(import.meta.url)
  const peggy = join(dirname(require.resolve('peggy/package.json')), 'bin/peggy.js')
  const generated = spawnSync(
    process.execPath,
    [peggy, '--format', 'es', 'grammar.peggy', '-o', '-'],
    { cwd: root, encoding: 'utf8' },
  )
  assert.equal(generated.status, 0, generated.stderr)
  const artifact = join(root, 'generated-parser.js')
  writeFileSync(artifact, await formatGeneratedSource(generated.stdout, artifact))
  const check = () =>
    spawnSync(process.execPath, [join(scripts, 'check-generated-parser.mjs')], {
      cwd: root,
      encoding: 'utf8',
    })
  return { root, build, manifest, artifact, check }
}

await test('parser gate accepts canonical Peggy output without writing', async (context) => {
  const fixture = await parserFixture(context)
  const before = statSync(fixture.artifact)
  const bytes = readFileSync(fixture.artifact)
  const checked = fixture.check()
  assert.equal(checked.status, 0, checked.stderr)
  assert.deepEqual(readFileSync(fixture.artifact), bytes)
  assert.equal(statSync(fixture.artifact).mtimeMs, before.mtimeMs)
})

await test('parser gate detects drift without rewriting the artifact', async (context) => {
  const fixture = await parserFixture(context)
  writeFileSync(fixture.artifact, '// stale artifact\n')
  const checked = fixture.check()
  assert.equal(checked.status, 1)
  assert.match(checked.stderr, /generated parser is stale/)
  assert.equal(readFileSync(fixture.artifact, 'utf8'), '// stale artifact\n')
})

await test('parser gate rejects shell-chained manifests instead of interpreting a different generator', async (context) => {
  const fixture = await parserFixture(context)
  writeFileSync(
    fixture.manifest,
    JSON.stringify({
      name: 'parser-fixture',
      type: 'module',
      scripts: { 'build:grammar': fixture.build + ' && echo wrong' },
    }),
  )
  const checked = fixture.check()
  assert.equal(checked.status, 1)
  assert.match(checked.stderr, /shell syntax this gate cannot interpret/)
})

await test('parser gate detects changed grammar without rewriting generated bytes', async (context) => {
  const fixture = await parserFixture(context)
  const before = readFileSync(fixture.artifact)
  writeFileSync(join(fixture.root, 'grammar.peggy'), 'start = "goodbye"')
  const checked = fixture.check()
  assert.equal(checked.status, 1)
  assert.match(checked.stderr, /generated parser is stale/)
  assert.deepEqual(readFileSync(fixture.artifact), before)
})

await test('parser gate cannot create a missing artifact', async (context) => {
  const fixture = await parserFixture(context)
  rmSync(fixture.artifact)
  const checked = fixture.check()
  assert.equal(checked.status, 1)
  assert.equal(existsSync(fixture.artifact), false)
})

await test('Peggy compilation failure leaves the existing parser unchanged', async (context) => {
  const fixture = await parserFixture(context)
  const before = readFileSync(fixture.artifact)
  writeFileSync(join(fixture.root, 'grammar.peggy'), 'start = "unterminated')
  const checked = fixture.check()
  assert.equal(checked.status, 1)
  assert.deepEqual(readFileSync(fixture.artifact), before)
})
